package com.src.main.utils;

import java.io.StringWriter;
import java.util.List;
import java.util.Objects;

import org.springframework.stereotype.Component;

import com.src.main.dto.InitializrProjectModel;
import com.src.main.dto.MavenDependency;

import io.spring.initializr.generator.buildsystem.Dependency;
import io.spring.initializr.generator.buildsystem.DependencyScope;
import io.spring.initializr.generator.buildsystem.maven.MavenBuild;
import io.spring.initializr.generator.buildsystem.maven.MavenBuildWriter;
import io.spring.initializr.generator.io.IndentingWriter;
import io.spring.initializr.generator.io.SimpleIndentStrategy;

@Component
public class InitializrPomGenerator {

	private final MavenBuildWriter writer = new MavenBuildWriter();

	public String generatePom(InitializrProjectModel model, List<MavenDependency> deps) {
		Objects.requireNonNull(model, "model must not be null");
		MavenBuild build = new MavenBuild();
		String groupId = req(model.groupId(), "groupId");
		String artifact = req(model.artifactId(), "artifactId");
		String bootVer = nz(model.bootVersion(), "3.3.5");
		String appVer = nz(model.version(), "0.0.1-SNAPSHOT");
		String name = nz(model.name(), artifact);
		String desc = nz(model.description(), "Generated by Rest App Generator");
		String packaging = nz(model.packaging(), "jar");
		String jdk = nz(model.jdkVersion(), "21");
		build.settings().parent("org.springframework.boot", "spring-boot-starter-parent", bootVer);
		build.settings().group(groupId);
		build.settings().artifact(artifact);
		build.settings().version(appVer);
		build.settings().name(name);
		build.settings().description(desc);
		build.settings().packaging(packaging);
		build.properties().version("java", jdk);
		if (deps != null) {
			for (MavenDependency md : deps) {
				if (md == null)
					continue;
				String g = trimOrNull(md.groupId());
				String a = trimOrNull(md.artifactId());
				if (g == null || a == null)
					continue;
				String id = g + ":" + a;
				build.dependencies().add(id, Dependency.withCoordinates(g, a).scope(toScope(md.scope())));
			}
		}
		build.dependencies().add("lombok", Dependency.withCoordinates("org.projectlombok", "lombok")
				.scope(DependencyScope.ANNOTATION_PROCESSOR).build());
		if ("jar".equalsIgnoreCase(packaging) == false && "war".equalsIgnoreCase(packaging)) {
			build.dependencies().add("org.springframework.boot:spring-boot-starter-tomcat",
					Dependency.withCoordinates("org.springframework.boot", "spring-boot-starter-tomcat")
							.scope(DependencyScope.PROVIDED_RUNTIME));
		}
		build.plugins().add("org.springframework.boot", "spring-boot-maven-plugin", p -> p.version(bootVer));
		StringWriter out = new StringWriter();
		try (IndentingWriter iw = new IndentingWriter(out, s -> "    ")) {
			MavenBuildWriter writer = new MavenBuildWriter();
			writer.writeTo(iw, build);
		} catch (Exception e) {
			throw new IllegalStateException("Failed to render pom.xml", e);
		}
		return out.toString();
	}

	private static String req(String v, String name) {
		if (v == null || v.isBlank())
			throw new IllegalArgumentException(name + " must not be null/blank");
		return v.trim();
	}

	private static String nz(String v, String dflt) {
		return (v == null || v.isBlank()) ? dflt : v.trim();
	}

	private static String trimOrNull(String v) {
		return (v == null || v.isBlank()) ? null : v.trim();
	}

	private DependencyScope toScope(String raw) {
		if (raw == null || raw.isBlank())
			return DependencyScope.COMPILE;
		switch (raw.trim().toLowerCase()) {
		case "annotation_processor":
		case "annotation-processor":
			return DependencyScope.ANNOTATION_PROCESSOR;
		case "compile_only":
		case "compile-only":
			return DependencyScope.COMPILE_ONLY;
		case "runtime":
		case "runtimeonly":
			return DependencyScope.RUNTIME;
		case "provided":
		case "providedruntime":
		case "provided_runtime":
			return DependencyScope.PROVIDED_RUNTIME;
		case "test":
		case "test_compile":
		case "test-compile":
			return DependencyScope.TEST_COMPILE;
		case "test_runtime":
		case "test-runtime":
			return DependencyScope.TEST_RUNTIME;
		default:
			return DependencyScope.COMPILE;
		}
	}
}