package com.src.main.util;

public interface ProjectMetaDataConstants {
	String ROOT_DIR = "rootDir";
	String GROUP_ID = "groupId";
	String ARTIFACT_ID = "artifactId";
	String NAME = "name";
	String DESCRIPTION = "description";
	String PACKAGE_NAME = "packageName";
	String BOOT_VERSION = "bootVersion";
	String VERSION = "version";
	String GENERATOR = "generator";
	String JDK_VERSION = "jdkVersion";
	String PACKAGING = "packaging";
	String DEPENDENCIES = "dependencies";
	String EXTRAS_OPENAPI = "extras.openapi";
	String EXTRAS_ANGULAR_INTEGRATION = "extras.angularIntegration";
	String BUILD_TOOL = "buildTool";
	
	String SPRING_BOOT_VERSION = "springBootVersion";
	String YAML = "yaml";
	
	
	String DEFAULT_BUILD_TOOL = "maven";
	String DEFAULT_ARTIFACT = "generated-api";
	String DEFAULT_GROUP = "com.src.main";
	String DEFAULT_VERSION = "0.0.1-SNAPSHOT";
	String DEFAULT_DESCRIPTION = "Project Generated By - Rest Generator";
	String DEFAULT_NAME = "demo-api";
	String DEFAULT_BOOT_VERSION = "3.3.5";
	String DEFAULT_APP_VERSION = "0.0.1-SNAPSHOT";
	String DEFAULT_PACKAGING = "jar";
	String DEFAULT_JDK = "21";
	String DEFAULT_GRADLE_GENERATOR = "groovy";
	String DEP_MGMT_PLUGIN_VERSION = "1.1.6";
	
}
