package com.src.main.sm.executor.node;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.regex.Pattern;

import org.springframework.statemachine.ExtendedState;

import com.src.main.dto.StepResult;
import com.src.main.sm.executor.common.LayeredSpecSupport;
import com.src.main.sm.executor.dto.DtoGenerationSupport;
import com.src.main.util.ProjectMetaDataConstants;
import com.src.main.util.ShippableModuleSupport;

final class NodeGenerationSupport {

	private static final Pattern LIST_PATTERN = Pattern.compile("^List\\s*<\\s*([A-Za-z0-9_$.]+)\\s*>$");

	private NodeGenerationSupport() {
	}

	@SuppressWarnings("unchecked")
	static NodeProjectContext resolveContext(ExtendedState state) {
		Object rootRaw = state.getVariables().get(ProjectMetaDataConstants.ROOT_DIR);
		if (rootRaw == null) {
			throw new IllegalArgumentException("Root directory not found in extended state.");
		}
		Path root = Path.of(String.valueOf(rootRaw));
		Map<String, Object> yaml = (Map<String, Object>) state.getVariables().get(ProjectMetaDataConstants.YAML);
		Map<String, Object> app = resolveSection(yaml, "app", "core", "app");
		Map<String, Object> node = resolveSection(yaml, "node", "runtime", "node");

		String artifactId = valueOrDefault(app.get(ProjectMetaDataConstants.ARTIFACT_ID),
				valueOrDefault(state.getVariables().get(ProjectMetaDataConstants.ARTIFACT_ID), "generated-node-app"));
		String appName = valueOrDefault(app.get(ProjectMetaDataConstants.NAME), artifactId);
		String description = valueOrDefault(app.get(ProjectMetaDataConstants.DESCRIPTION), "Generated by Rest App Generator");
		String version = valueOrDefault(app.get(ProjectMetaDataConstants.VERSION), "1.0.0");
		int port = parsePort(node.get("port"), 3000);
		String packageManager = normalizePackageManager(node.get("packageManager"));
		boolean dockerEnabled = parseBoolean(firstNonNull(node.get("docker"), yaml != null ? yaml.get("useDockerCompose") : null), false);

		List<NodeEnumDefinition> enums = extractEnums(yaml);
		List<NodeDtoDefinition> dtos = extractDtos(yaml);
		List<NodeModelDefinition> models = extractModels(yaml);
		return new NodeProjectContext(root, appName, artifactId, description, version, port, packageManager, dockerEnabled, enums, dtos, models);
	}

	@SuppressWarnings("unchecked")
	private static Map<String, Object> resolveSection(Map<String, Object> yaml, String topLevelKey, String parentKey,
			String nestedKey) {
		if (yaml != null && yaml.get(topLevelKey) instanceof Map<?, ?> topLevelRaw) {
			return (Map<String, Object>) topLevelRaw;
		}
		if (yaml != null && yaml.get(parentKey) instanceof Map<?, ?> parentRaw) {
			Object nested = ((Map<String, Object>) parentRaw).get(nestedKey);
			if (nested instanceof Map<?, ?> nestedRaw) {
				return (Map<String, Object>) nestedRaw;
			}
		}
		return Map.of();
	}

	static StepResult success(String status) {
		return StepResult.ok(Map.of("status", status));
	}

	static void writeFile(Path root, String relativePath, String content) throws Exception {
		Path output = root.resolve(relativePath);
		Files.createDirectories(output.getParent());
		Files.writeString(output, content, StandardCharsets.UTF_8);
	}

	static String toPascalCase(String raw) {
		if (raw == null || raw.isBlank()) {
			return "GeneratedItem";
		}
		String normalized = raw.replace('-', ' ').replace('_', ' ');
		StringBuilder result = new StringBuilder();
		for (String token : normalized.trim().split("\\s+")) {
			if (token.isBlank()) {
				continue;
			}
			String cleaned = sanitizeIdentifier(token);
			if (cleaned.isBlank()) {
				continue;
			}
			result.append(Character.toUpperCase(cleaned.charAt(0)));
			if (cleaned.length() > 1) {
				result.append(cleaned.substring(1));
			}
		}
		return result.isEmpty() ? "GeneratedItem" : result.toString();
	}

	static String toCamelCase(String raw) {
		String pascal = toPascalCase(raw);
		return Character.toLowerCase(pascal.charAt(0)) + pascal.substring(1);
	}

	static String toKebabCase(String raw) {
		String cleaned = sanitizeIdentifier(valueOrDefault(raw, "generated-item"));
		if (cleaned.isBlank()) {
			return "generated-item";
		}
		StringBuilder result = new StringBuilder();
		for (int i = 0; i < cleaned.length(); i++) {
			char ch = cleaned.charAt(i);
			if (Character.isUpperCase(ch) && i > 0) {
				result.append('-');
			}
			result.append(Character.toLowerCase(ch));
		}
		return result.toString();
	}

	static String sanitizeIdentifier(String raw) {
		if (raw == null) {
			return "";
		}
		StringBuilder result = new StringBuilder();
		for (char ch : raw.trim().toCharArray()) {
			if (Character.isLetterOrDigit(ch) || ch == '_') {
				result.append(ch);
			}
		}
		if (result.isEmpty()) {
			return "";
		}
		if (Character.isDigit(result.charAt(0))) {
			result.insert(0, '_');
		}
		return result.toString();
	}

	static String mapToTypeScriptType(String rawType) {
		String type = valueOrDefault(rawType, "string").trim();
		var matcher = LIST_PATTERN.matcher(type);
		if (matcher.matches()) {
			return mapToTypeScriptType(matcher.group(1)) + "[]";
		}
		String normalized = type.toLowerCase(Locale.ROOT);
		switch (normalized) {
		case "string":
		case "uuid":
		case "date":
		case "localdate":
		case "localdatetime":
		case "offsetdatetime":
		case "instant":
			return "string";
		case "int":
		case "integer":
		case "long":
		case "double":
		case "float":
		case "bigdecimal":
		case "short":
		case "byte":
			return "number";
		case "boolean":
			return "boolean";
		default:
			return "unknown";
		}
	}

	static String indent(String value, int spaces) {
		String prefix = " ".repeat(Math.max(0, spaces));
		return value.lines().map(line -> prefix + line).reduce((a, b) -> a + "\n" + b).orElse("");
	}

	static List<String> extractSelectedShippedModules(Map<String, Object> yaml) {
		List<String> selected = new ArrayList<>();
		for (String dependency : LayeredSpecSupport.resolveDependencies(yaml)) {
			if (ShippableModuleSupport.isVisibleModule(dependency)) {
				selected.add(dependency);
			}
		}
		return selected;
	}

	@SuppressWarnings("unchecked")
	static Map<String, Object> extractModuleConfigs(Map<String, Object> yaml) {
		if (yaml == null || !(yaml.get("moduleConfigs") instanceof Map<?, ?> rawConfigs)) {
			return Map.of();
		}
		Map<String, Object> configs = new LinkedHashMap<>();
		for (Map.Entry<?, ?> entry : rawConfigs.entrySet()) {
			if (entry.getKey() == null) {
				continue;
			}
			String moduleId = String.valueOf(entry.getKey()).trim();
			if (!ShippableModuleSupport.isShippableModule(moduleId)) {
				continue;
			}
			Object value = entry.getValue();
			if (value instanceof Map<?, ?> mapValue) {
				configs.put(moduleId, new LinkedHashMap<>((Map<String, Object>) mapValue));
			} else if (value instanceof List<?> listValue) {
				configs.put(moduleId, new ArrayList<>(listValue));
			} else if (value != null) {
				configs.put(moduleId, value);
			} else {
				configs.put(moduleId, Collections.emptyMap());
			}
		}
		return configs;
	}

	private static Object firstNonNull(Object first, Object second) {
		return first != null ? first : second;
	}

	private static boolean parseBoolean(Object value, boolean defaultValue) {
		if (value == null) {
			return defaultValue;
		}
		if (value instanceof Boolean bool) {
			return bool;
		}
		return Boolean.parseBoolean(String.valueOf(value));
	}

	private static int parsePort(Object raw, int defaultPort) {
		if (raw == null) {
			return defaultPort;
		}
		try {
			return Integer.parseInt(String.valueOf(raw));
		} catch (NumberFormatException ex) {
			return defaultPort;
		}
	}

	private static String normalizePackageManager(Object raw) {
		String packageManager = valueOrDefault(raw, "npm").trim().toLowerCase(Locale.ROOT);
		return Set.of("npm", "pnpm", "yarn").contains(packageManager) ? packageManager : "npm";
	}

	@SuppressWarnings("unchecked")
	private static List<NodeEnumDefinition> extractEnums(Map<String, Object> yaml) {
		List<NodeEnumDefinition> enums = new ArrayList<>();
		if (yaml == null || !(yaml.get("enums") instanceof List<?> items)) {
			return enums;
		}
		for (Object item : items) {
			if (!(item instanceof Map<?, ?> rawMap)) {
				continue;
			}
			Map<String, Object> enumMap = (Map<String, Object>) rawMap;
			String name = toPascalCase(valueOrDefault(enumMap.get("name"), ""));
			if (name.isBlank()) {
				continue;
			}
			List<String> constants = new ArrayList<>();
			if (enumMap.get("constants") instanceof List<?> rawConstants) {
				for (Object rawConstant : rawConstants) {
					String constant = sanitizeIdentifier(valueOrDefault(rawConstant, "")).toUpperCase(Locale.ROOT);
					if (!constant.isBlank()) {
						constants.add(constant);
					}
				}
			}
			if (!constants.isEmpty()) {
				enums.add(new NodeEnumDefinition(name, constants));
			}
		}
		return enums;
	}

	@SuppressWarnings("unchecked")
	private static List<NodeDtoDefinition> extractDtos(Map<String, Object> yaml) {
		List<NodeDtoDefinition> dtos = new ArrayList<>();
		if (yaml == null || !(yaml.get("dtos") instanceof List<?> items)) {
			return dtos;
		}
		for (Object item : items) {
			if (!(item instanceof Map<?, ?> rawMap)) {
				continue;
			}
			Map<String, Object> dtoMap = (Map<String, Object>) rawMap;
			String name = toPascalCase(valueOrDefault(dtoMap.get("name"), ""));
			if (name.isBlank()) {
				continue;
			}
			String dtoType = valueOrDefault(dtoMap.get("type"), "request").trim().toLowerCase(Locale.ROOT);
			dtos.add(new NodeDtoDefinition(
					name,
					dtoType,
					extractFields(dtoMap.get("fields")),
					extractClassConstraints(dtoMap.get("classConstraints"))));
		}
		return dtos;
	}

	@SuppressWarnings("unchecked")
	private static List<NodeModelDefinition> extractModels(Map<String, Object> yaml) {
		List<NodeModelDefinition> models = new ArrayList<>();
		if (yaml == null || !(yaml.get("models") instanceof List<?> items)) {
			return models;
		}
		for (Object item : items) {
			if (!(item instanceof Map<?, ?> rawMap)) {
				continue;
			}
			Map<String, Object> modelMap = (Map<String, Object>) rawMap;
			String name = toPascalCase(valueOrDefault(modelMap.get("name"), ""));
			if (name.isBlank()) {
				continue;
			}
			List<NodeFieldDefinition> fields = new ArrayList<>();
			fields.add(new NodeFieldDefinition("id", "UUID", "string", false, List.of()));
			fields.addAll(extractFields(modelMap.get("fields")));
			models.add(new NodeModelDefinition(name, deduplicateFields(fields), extractRestConfig(modelMap, name)));
		}
		return models;
	}

	@SuppressWarnings("unchecked")
	private static List<NodeFieldDefinition> extractFields(Object rawFields) {
		List<NodeFieldDefinition> fields = new ArrayList<>();
		if (!(rawFields instanceof List<?> items)) {
			return fields;
		}
		for (Object item : items) {
			if (!(item instanceof Map<?, ?> rawMap)) {
				continue;
			}
			Map<String, Object> fieldMap = (Map<String, Object>) rawMap;
			String name = sanitizeIdentifier(valueOrDefault(fieldMap.get("name"), ""));
			if (name.isBlank()) {
				continue;
			}
			String rawType = valueOrDefault(fieldMap.get("type"), "String");
			List<NodeConstraintDefinition> constraints = extractFieldConstraints(fieldMap.get("constraints"), name);
			String tsType = mapToTypeScriptType(rawType);
			boolean optional = !hasRequiredConstraint(constraints);
			fields.add(new NodeFieldDefinition(name, rawType, tsType, optional, constraints));
		}
		return deduplicateFields(fields);
	}

	private static List<NodeFieldDefinition> deduplicateFields(List<NodeFieldDefinition> fields) {
		List<NodeFieldDefinition> unique = new ArrayList<>();
		Set<String> names = new LinkedHashSet<>();
		for (NodeFieldDefinition field : fields) {
			if (names.add(field.name())) {
				unique.add(field);
			}
		}
		return unique;
	}

	private static boolean hasRequiredConstraint(List<NodeConstraintDefinition> constraints) {
		for (NodeConstraintDefinition constraint : constraints) {
			if (isRequiredConstraint(constraint.kind())) {
				return true;
			}
		}
		return false;
	}

	private static List<NodeConstraintDefinition> extractFieldConstraints(Object rawConstraints, String fieldName) {
		List<NodeConstraintDefinition> constraints = new ArrayList<>();
		for (Map<String, Object> normalized : DtoGenerationSupport.normalizeConstraints(rawConstraints)) {
			String kind = valueOrDefault(normalized.get("kind"), "");
			if (kind.isBlank()) {
				continue;
			}
			Map<String, Object> params = new LinkedHashMap<>(normalized);
			params.remove("kind");
			String key = valueOrDefault(normalized.get("key"), "");
			String message = valueOrDefault(
					normalized.get("defaultMessage"),
					key.isBlank() ? DtoGenerationSupport.defaultMessage(kind, fieldName) : key);
			constraints.add(new NodeConstraintDefinition(kind, immutableParams(params), key, message));
		}
		return constraints;
	}

	private static List<NodeConstraintDefinition> extractClassConstraints(Object rawConstraints) {
		List<NodeConstraintDefinition> constraints = new ArrayList<>();
		for (Map<String, Object> normalized : DtoGenerationSupport.normalizeClassConstraints(rawConstraints)) {
			String kind = valueOrDefault(normalized.get("kind"), "");
			if (kind.isBlank()) {
				continue;
			}
			Map<String, Object> params = new LinkedHashMap<>(normalized);
			params.remove("kind");
			String key = valueOrDefault(normalized.get("key"), "");
			String message = valueOrDefault(
					normalized.get("defaultMessage"),
					key.isBlank() ? DtoGenerationSupport.defaultClassMessage(normalized) : key);
			constraints.add(new NodeConstraintDefinition(kind, immutableParams(params), key, message));
		}
		return constraints;
	}

	private static Map<String, Object> immutableParams(Map<String, Object> params) {
		Map<String, Object> cleaned = new LinkedHashMap<>();
		for (Map.Entry<String, Object> entry : params.entrySet()) {
			if (entry.getValue() != null) {
				cleaned.put(entry.getKey(), entry.getValue());
			}
		}
		return Map.copyOf(cleaned);
	}

	@SuppressWarnings("unchecked")
	private static NodeRestConfig extractRestConfig(Map<String, Object> modelMap, String modelName) {
		Object rawRest = modelMap.get("rest");
		if (!(rawRest instanceof Map<?, ?> restRaw)) {
			String defaultBasePath = "/api/" + toKebabCase(modelName);
			return new NodeRestConfig(defaultBasePath, true, true, true, true, true, "", "", "");
		}

		Map<String, Object> rest = (Map<String, Object>) restRaw;
		Map<String, Object> methods = rest.get("methods") instanceof Map<?, ?> methodsRaw
				? (Map<String, Object>) methodsRaw
				: Map.of();
		String basePath = valueOrDefault(rest.get("basePath"), "/api/" + toKebabCase(modelName));
		return new NodeRestConfig(
				basePath.startsWith("/") ? basePath : "/" + basePath,
				methods.isEmpty() || methods.containsKey("list"),
				methods.isEmpty() || methods.containsKey("get"),
				methods.isEmpty() || methods.containsKey("create"),
				methods.isEmpty() || methods.containsKey("update"),
				methods.isEmpty() || methods.containsKey("delete"),
				extractRequestDtoName(methods.get("create")),
				extractRequestDtoName(methods.get("update")),
				extractRequestDtoName(methods.get("patch")));
	}

	@SuppressWarnings("unchecked")
	private static String extractRequestDtoName(Object rawMethod) {
		if (!(rawMethod instanceof Map<?, ?> methodRaw)) {
			return "";
		}
		Map<String, Object> method = (Map<String, Object>) methodRaw;
		if (!(method.get("request") instanceof Map<?, ?> requestRaw)) {
			return "";
		}
		Map<String, Object> request = (Map<String, Object>) requestRaw;
		return valueOrDefault(request.get("dtoName"), "");
	}

	private static boolean isRequiredConstraint(String rawConstraint) {
		String normalized = valueOrDefault(rawConstraint, "").trim().toLowerCase(Locale.ROOT);
		return normalized.equals("notnull") || normalized.equals("not_null") || normalized.equals("notblank")
				|| normalized.equals("not_blank") || normalized.equals("notempty") || normalized.equals("not_empty");
	}

	private static String valueOrDefault(Object value, String defaultValue) {
		String resolved = value == null ? null : String.valueOf(value).trim();
		return resolved == null || resolved.isBlank() ? defaultValue : resolved;
	}
}
