package com.src.main.sm.executor;

import static java.nio.charset.StandardCharsets.UTF_8;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

import org.springframework.statemachine.ExtendedState;
import org.springframework.stereotype.Component;

import com.src.main.dto.StepResult;
import com.src.main.sm.config.StepExecutor;
import com.src.main.sm.executor.common.GenerationLanguage;
import com.src.main.sm.executor.common.GenerationLanguageResolver;
import com.src.main.util.ProjectMetaDataConstants;

@Component
public class NodeGenerationExecutor implements StepExecutor {

	private static final String NODE_TEMPLATE_BASE = "templates/languages/node/project/";

	private final TemplateEngine templateEngine;

	public NodeGenerationExecutor(TemplateEngine templateEngine) {
		this.templateEngine = templateEngine;
	}

	@Override
	@SuppressWarnings("unchecked")
	public StepResult execute(ExtendedState data) {
		try {
			Object rootRaw = data.getVariables().get(ProjectMetaDataConstants.ROOT_DIR);
			if (rootRaw == null) {
				return StepResult.error("NODE_GENERATION", "Root directory not found in extended state.");
			}
			Path root = Path.of(String.valueOf(rootRaw));
			Map<String, Object> yaml = (Map<String, Object>) data.getVariables().get(ProjectMetaDataConstants.YAML);
			GenerationLanguage language = GenerationLanguageResolver.resolveFromYaml(yaml);
			if (language != GenerationLanguage.NODE) {
				return StepResult.ok(Map.of("status", "Skipped for " + language.name()));
			}

			Map<String, Object> app = yaml != null && yaml.get("app") instanceof Map<?, ?> map
					? (Map<String, Object>) map
					: Map.of();
			String artifact = valueOrDefault(app.get("artifactId"),
					valueOrDefault(data.getVariables().get(ProjectMetaDataConstants.ARTIFACT_ID), "generated-node-app"));
			String appName = valueOrDefault(app.get("name"), artifact);
			String description = valueOrDefault(app.get("description"), "Generated by Rest App Generator");
			String version = valueOrDefault(app.get("version"), "1.0.0");
			String groupId = valueOrDefault(app.get("groupId"),
					valueOrDefault(data.getVariables().get(ProjectMetaDataConstants.GROUP_ID), "com.example"));

			Set<String> modelNames = extractModelNames(yaml);
			if (modelNames.isEmpty()) {
				modelNames.add("User");
			}

			createDirectoryLayout(root);
			writeStaticFiles(root, buildBaseModel(appName, artifact, description, version, groupId));
			writeDynamicEntityFiles(root, modelNames);
			writeDynamicRoutesRegistry(root, modelNames);

			return StepResult.ok(Map.of("status", "Node project scaffold generated"));
		} catch (Exception ex) {
			return StepResult.error("NODE_GENERATION", ex.getMessage());
		}
	}

	private void createDirectoryLayout(Path root) throws Exception {
		List<String> directories = List.of(
				"app/config",
				"app/database",
				"app/routes",
				"app/utils",
				"app/middleware",
				"app/models",
				"app/controllers",
				"app/helpers",
				"app/views/layouts",
				"app/views/partials",
				"app/views/support",
				"app/views/documentation",
				"public/dist",
				"public/images/dashboard",
				"public/images/auth",
				"public/images/documentation",
				"samples",
				"src/javascript",
				"src/css");
		for (String dir : directories) {
			Files.createDirectories(root.resolve(dir));
		}
	}

	private void writeStaticFiles(Path root, Map<String, Object> model) throws Exception {
		Map<String, String> staticTemplates = new LinkedHashMap<>();
		staticTemplates.put("server.js", "server.js.mustache");
		staticTemplates.put("package.json", "package.json.mustache");
		staticTemplates.put(".env", "env.mustache");
		staticTemplates.put(".gitignore", "gitignore.mustache");
		staticTemplates.put("samples/.env.sample", "samples/env.sample.mustache");
		staticTemplates.put("samples/db.conf.sample", "samples/db.conf.sample.mustache");
		staticTemplates.put("samples/app.conf.sample", "samples/app.conf.sample.mustache");
		staticTemplates.put("samples/app.keys.sample", "samples/app.keys.sample.mustache");
		staticTemplates.put("app/config/db.conf.js", "app/config/db.conf.js.mustache");
		staticTemplates.put("app/config/app.conf.js", "app/config/app.conf.js.mustache");
		staticTemplates.put("app/config/app.keys.js", "app/config/app.keys.js.mustache");
		staticTemplates.put("app/config/db.keys.js", "app/config/db.keys.js.mustache");
		staticTemplates.put("app/config/init.js", "app/config/init.js.mustache");
		staticTemplates.put("app/database/Redis.database.js", "app/database/redis.database.js.mustache");
		staticTemplates.put("app/database/Mongo.database.js", "app/database/mongo.database.js.mustache");
		staticTemplates.put("app/database/init.js", "app/database/init.js.mustache");
		staticTemplates.put("app/routes/App.routes.js", "app/routes/app.routes.js.mustache");
		staticTemplates.put("app/routes/Auth.routes.js", "app/routes/auth.routes.js.mustache");
		staticTemplates.put("app/routes/Dashboard.routes.js", "app/routes/dashboard.routes.js.mustache");
		staticTemplates.put("app/utils/Logger.util.js", "app/utils/logger.util.js.mustache");
		staticTemplates.put("app/middleware/App.middleware.js", "app/middleware/app.middleware.js.mustache");
		staticTemplates.put("app/middleware/ErrorHandler.middleware.js", "app/middleware/error-handler.middleware.js.mustache");
		staticTemplates.put("app/middleware/init.js", "app/middleware/init.js.mustache");
		staticTemplates.put("app/controllers/App.controller.js", "app/controllers/app.controller.js.mustache");
		staticTemplates.put("app/helpers/App.helper.js", "app/helpers/app.helper.js.mustache");
		staticTemplates.put("app/views/index.ejs", "app/views/index.ejs.mustache");
		staticTemplates.put("app/views/about.ejs", "app/views/about.ejs.mustache");
		staticTemplates.put("app/views/contact.ejs", "app/views/contact.ejs.mustache");
		staticTemplates.put("app/views/support/index.ejs", "app/views/support/index.ejs.mustache");
		staticTemplates.put("app/views/documentation/index.ejs", "app/views/documentation/index.ejs.mustache");
		staticTemplates.put("public/sitemap.xml", "public/sitemap.xml.mustache");

		for (Map.Entry<String, String> entry : staticTemplates.entrySet()) {
			String outputPath = entry.getKey();
			String templatePath = NODE_TEMPLATE_BASE + entry.getValue();
			writeRendered(root.resolve(outputPath), templatePath, model);
		}
	}

	private void writeDynamicEntityFiles(Path root, Set<String> modelNames) throws Exception {
		for (String rawModelName : modelNames) {
			String modelName = toPascalCase(rawModelName);
			Map<String, Object> model = new HashMap<>();
			model.put("modelName", modelName);
			model.put("modelNameLower", Character.toLowerCase(modelName.charAt(0)) + modelName.substring(1));
			model.put("routePath", modelName.toLowerCase(Locale.ROOT));

			writeRendered(root.resolve("app/models/" + modelName + ".model.js"),
					NODE_TEMPLATE_BASE + "app/models/entity.model.js.mustache",
					model);
			writeRendered(root.resolve("app/controllers/" + modelName + ".controller.js"),
					NODE_TEMPLATE_BASE + "app/controllers/entity.controller.js.mustache",
					model);
			writeRendered(root.resolve("app/routes/" + modelName + ".routes.js"),
					NODE_TEMPLATE_BASE + "app/routes/entity.routes.js.mustache",
					model);
		}
	}

	private void writeDynamicRoutesRegistry(Path root, Set<String> modelNames) throws Exception {
		List<Map<String, Object>> routes = new ArrayList<>();
		for (String rawModelName : modelNames) {
			String modelName = toPascalCase(rawModelName);
			Map<String, Object> route = new HashMap<>();
			route.put("modelName", modelName);
			route.put("routePath", modelName.toLowerCase(Locale.ROOT));
			routes.add(route);
		}
		Map<String, Object> model = new HashMap<>();
		model.put("entityRoutes", routes);
		writeRendered(root.resolve("app/routes/init.js"), NODE_TEMPLATE_BASE + "app/routes/init.js.mustache", model);
	}

	private Map<String, Object> buildBaseModel(
			String appName,
			String artifactId,
			String description,
			String version,
			String groupId) {
		Map<String, Object> model = new HashMap<>();
		model.put("appName", appName);
		model.put("artifactId", artifactId);
		model.put("description", description);
		model.put("version", version);
		model.put("groupId", groupId);
		return model;
	}

	@SuppressWarnings("unchecked")
	private Set<String> extractModelNames(Map<String, Object> yaml) {
		Set<String> names = new LinkedHashSet<>();
		if (yaml == null) {
			return names;
		}
		Object modelsRaw = yaml.get("models");
		if (!(modelsRaw instanceof List<?> models)) {
			return names;
		}
		for (Object modelRaw : models) {
			if (!(modelRaw instanceof Map<?, ?> mapRaw)) {
				continue;
			}
			Map<String, Object> map = (Map<String, Object>) mapRaw;
			String name = valueOrDefault(map.get("name"), "");
			if (!name.isBlank()) {
				names.add(name.trim());
			}
		}
		return names;
	}

	private void writeRendered(Path output, String templatePath, Map<String, Object> model) throws Exception {
		Files.createDirectories(output.getParent());
		String content = templateEngine.render(templatePath, model);
		Files.writeString(output, content, UTF_8);
	}

	private static String valueOrDefault(Object value, String fallback) {
		String resolved = value == null ? "" : String.valueOf(value).trim();
		return resolved.isBlank() ? fallback : resolved;
	}

	private static String toPascalCase(String raw) {
		String value = valueOrDefault(raw, "Entity").replaceAll("[^a-zA-Z0-9]", " ");
		String[] parts = value.trim().split("\\s+");
		StringBuilder sb = new StringBuilder();
		for (String part : parts) {
			if (part.isBlank()) {
				continue;
			}
			sb.append(Character.toUpperCase(part.charAt(0)));
			if (part.length() > 1) {
				sb.append(part.substring(1));
			}
		}
		return sb.length() == 0 ? "Entity" : sb.toString();
	}
}
