package com.src.main.service;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.springframework.stereotype.Service;

import com.src.main.common.util.JsonYamlConverterUtil;

@Service
public class ProjectDraftSpecMapperService {

	private static final List<String> ACTUATOR_ENDPOINT_OPTIONS = List.of(
			"health", "shutdown", "metrics", "info", "env", "beans", "mappings", "loggers",
			"threaddump", "heapdump", "prometheus", "conditions", "configprops", "caches", "scheduledtasks");
	private static final List<String> DEFAULT_ACTUATOR_ENDPOINTS = List.of("health", "metrics", "info");
	private static final Pattern CONSTRAINT_PARAM_PATTERN = Pattern.compile("^\\d+");

	public Map<String, Object> buildSpec(Map<String, Object> project) {
		String generatorLanguage = trimmed(getNested(project, "settings", "language"));
		if (generatorLanguage.isBlank()) {
			generatorLanguage = "java";
		}
		boolean isNodeProject = "node".equalsIgnoreCase(generatorLanguage);
		boolean isPythonProject = "python".equalsIgnoreCase(generatorLanguage);
		boolean usesLightweightRuntime = isNodeProject || isPythonProject;
		String projectGroup = trimmed(getNested(project, "settings", "projectGroup"));
		if (projectGroup.isBlank()) {
			projectGroup = "io.bootrid";
		}
		String projectName = trimmed(getNested(project, "settings", "projectName"));
		if (projectName.isBlank()) {
			projectName = "demo-app";
		}
		String projectDescription = trimmed(getNested(project, "settings", "projectDescription"));
		if (projectDescription.isBlank()) {
			projectDescription = "Generated by Rest App Generator";
		}
		String databaseCode = toDatabaseCode(getNested(project, "database", "database"));
		String javaVersion = trimmed(getNested(project, "preferences", "javaVersion"));
		if (javaVersion.isBlank()) {
			javaVersion = "17";
		}
		boolean useJavaRecordsForDtos = supportsJavaRecords(javaVersion);

		Map<String, Object> app = linkedMap();
		app.put("name", projectName);
		app.put("groupId", projectGroup);
		String artifactId = toArtifactId(projectName);
		app.put("artifactId", artifactId);
		app.put("description", projectDescription);
		app.put("version", "0.0.1-SNAPSHOT");
		app.put("jdkVersion", javaVersion);
		app.put("buildTool", defaultIfBlank(trimmed(getNested(project, "settings", "buildType")), "gradle"));
		app.put("generator", generatorLanguage);

		boolean includeControllersSpec = asBoolean(getNested(project, "preferences", "configureApi"))
				&& getNested(project, "controllers", "enabled") != Boolean.FALSE
				&& hasNamedControllersConfig(getNestedMap(project, "controllers", "config"));
		RestSpecSection restSpecSection = buildRestSpecSection(
				getNestedList(project, "entities"),
				getNestedMap(project, "controllers", "config"),
				includeControllersSpec);

		Map<String, Object> spec = linkedMap();
		spec.put("app", app);
		spec.put("database", databaseCode);
		spec.put("dbType", resolveDatabaseType(getNested(project, "database", "dbType"), databaseCode));
		spec.put("applFormat", defaultIfBlank(trimmed(getNested(project, "preferences", "applFormat")), "yaml"));
		spec.put("enableOpenapi", usesLightweightRuntime ? false : asBoolean(getNested(project, "preferences", "enableOpenAPI")));
		spec.put("enableActuator", usesLightweightRuntime ? false : asBoolean(getNested(project, "preferences", "enableActuator")));
		Object enableLombokRaw = getNested(project, "preferences", "enableLombok");
		spec.put("enableLombok", usesLightweightRuntime ? false
				: (enableLombokRaw == null
						? asBoolean(getNested(project, "preferences", "optionalLombok"))
						: asBoolean(enableLombokRaw)));
		spec.put("useDockerCompose", asBoolean(getNested(project, "preferences", "useDockerCompose")));
		spec.put("packages", usesLightweightRuntime ? "technical"
				: defaultIfBlank(trimmed(getNested(project, "preferences", "packages")), "technical"));
		spec.put("profiles", mapProfiles(getNested(project, "preferences", "profiles")));
		spec.put("dependencies", extractDependencies(
				String.valueOf(project.getOrDefault("dependencies", "")),
				asStringList(project.get("selectedDependencies"))));
		spec.put("basePackage", projectGroup);
		spec.put("models", mapModels(getNestedList(project, "entities"), getNestedList(project, "relations"),
				restSpecSection.entityToSpecName));
		spec.put("dtos", mapDtos(getNestedList(project, "dataObjects"), useJavaRecordsForDtos));
		spec.put("enums", mapEnums(getNestedList(project, "enums")));

		List<Map<String, Object>> mergedMappers = mergeMapperSpecs(
				mapMappers(getNestedList(project, "mappers")),
				mapAutoRequestMappers(getNestedList(project, "entities"), getNestedList(project, "dataObjects")));
		if (!mergedMappers.isEmpty()) {
			spec.put("mappers", mergedMappers);
		}

		if (!"NONE".equals(databaseCode)) {
			spec.put("dbGeneration", defaultIfBlank(trimmed(getNested(project, "database", "dbGeneration")), "Hibernate (update)"));
			spec.put("pluralizeTableNames", asBoolean(getNested(project, "database", "pluralizeTableNames")));
		}

		if (isNodeProject) {
			Map<String, Object> node = linkedMap();
			node.put("packageManager", defaultIfBlank(trimmed(getNested(project, "settings", "packageManager")), "npm"));
			node.put("port", toInt(getNested(project, "settings", "serverPort"), 3000));
			node.put("docker", asBoolean(getNested(project, "preferences", "useDockerCompose")));
			spec.put("node", node);
		}

		if (!usesLightweightRuntime && asBoolean(getNested(project, "preferences", "enableActuator"))) {
			List<String> actuatorConfigOptions = getActuatorConfigurationOptions(getNested(project, "preferences", "profiles"));
			Map<String, List<String>> actuatorConfigurations = sanitizeActuatorConfigurations(
					nonNull(getNested(project, "actuator", "configurations"), getNested(project, "actuator", "endpoints")),
					actuatorConfigOptions);
			Map<String, Object> actuator = linkedMap();
			Map<String, Object> endpoints = linkedMap();
			endpoints.put("include", sanitizeActuatorEndpoints(actuatorConfigurations.get("default")));
			actuator.put("endpoints", endpoints);

			Map<String, Object> profiles = linkedMap();
			for (Map.Entry<String, List<String>> entry : actuatorConfigurations.entrySet()) {
				if ("default".equals(entry.getKey())) {
					continue;
				}
				Map<String, Object> profileConfig = linkedMap();
				Map<String, Object> profileEndpoints = linkedMap();
				profileEndpoints.put("include", sanitizeActuatorEndpoints(entry.getValue()));
				profileConfig.put("endpoints", profileEndpoints);
				profiles.put(entry.getKey(), profileConfig);
			}
			actuator.put("profiles", profiles);
			spec.put("actuator", actuator);
		}

		if (asBoolean(getNested(project, "preferences", "configureApi"))
				&& getNested(project, "controllers", "enabled") != Boolean.FALSE
				&& hasNamedControllersConfig(getNestedMap(project, "controllers", "config"))) {
			Map<String, Object> controllersConfig = mapRestConfig(getNestedMap(project, "controllers", "config"));
			if (controllersConfig != null) {
				spec.put("controllers", controllersConfig);
			}
		}

		if (!restSpecSection.specs.isEmpty()) {
			spec.put("rest-spec", restSpecSection.specs);
		}

		spec.put("core", buildCoreSection(project, artifactId, projectDescription, projectName, databaseCode,
				restSpecSection.specs, mergedMappers));
		spec.put("runtime", buildRuntimeSection(project, generatorLanguage, projectGroup, artifactId, javaVersion,
				databaseCode));

		removeEmptyList(spec, "dependencies");
		removeEmptyList(spec, "models");
		removeEmptyList(spec, "dtos");
		removeEmptyList(spec, "enums");

		return spec;
	}

	private Map<String, Object> buildCoreSection(Map<String, Object> project, String artifactId,
			String projectDescription, String projectName, String databaseCode, List<Map<String, Object>> restSpecs,
			List<Map<String, Object>> mergedMappers) {
		Map<String, Object> core = linkedMap();

		Map<String, Object> app = linkedMap();
		app.put("name", projectName);
		app.put("description", projectDescription);
		app.put("artifactId", artifactId);
		core.put("app", app);

		Map<String, Object> database = linkedMap();
		database.put("database", databaseCode);
		database.put("dbType", resolveDatabaseType(getNested(project, "database", "dbType"), databaseCode));
		if (!"NONE".equals(databaseCode)) {
			database.put("dbGeneration",
					defaultIfBlank(trimmed(getNested(project, "database", "dbGeneration")), "Hibernate (update)"));
			database.put("pluralizeTableNames", asBoolean(getNested(project, "database", "pluralizeTableNames")));
		}
		core.put("database", database);

		Map<String, Object> domain = linkedMap();
		domain.put("models", mapModels(getNestedList(project, "entities"), getNestedList(project, "relations"),
				Collections.emptyMap()));
		domain.put("dtos", mapDtos(getNestedList(project, "dataObjects"), true));
		domain.put("enums", mapEnums(getNestedList(project, "enums")));
		if (!mergedMappers.isEmpty()) {
			domain.put("mappers", mergedMappers);
		}
		removeEmptyList(domain, "models");
		removeEmptyList(domain, "dtos");
		removeEmptyList(domain, "enums");
		core.put("domain", domain);

		Map<String, Object> api = linkedMap();
		if (!restSpecs.isEmpty()) {
			api.put("restSpec", restSpecs);
		}
		Object controllersEnabled = getNested(project, "controllers", "enabled");
		if (controllersEnabled != null) {
			api.put("controllersEnabled", asBoolean(controllersEnabled));
		}
		core.put("api", api);

		Map<String, Object> modules = linkedMap();
		List<String> dependencies = extractDependencies(String.valueOf(project.getOrDefault("dependencies", "")),
				asStringList(project.get("selectedDependencies")));
		List<String> selectedModules = dependencies.stream()
				.filter(dep -> List.of("auth", "rbac", "subscription", "state-machine").contains(dep))
				.toList();
		List<String> customDependencies = dependencies.stream()
				.filter(dep -> !selectedModules.contains(dep))
				.toList();
		modules.put("selected", selectedModules);
		if (!customDependencies.isEmpty()) {
			modules.put("customDependencies", customDependencies);
		}
		Object moduleConfigs = project.get("moduleConfigs");
		if (moduleConfigs instanceof Map<?, ?> configs && !configs.isEmpty()) {
			modules.put("config", configs);
		}
		core.put("modules", modules);

		return core;
	}

	private Map<String, Object> buildRuntimeSection(Map<String, Object> project, String generatorLanguage,
			String projectGroup, String artifactId, String javaVersion, String databaseCode) {
		Map<String, Object> runtime = linkedMap();
		runtime.put("active", generatorLanguage);

		Map<String, Object> javaRuntime = linkedMap();
		javaRuntime.put("packageName", projectGroup);
		javaRuntime.put("groupId", projectGroup);
		javaRuntime.put("artifactId", artifactId);
		javaRuntime.put("buildTool", defaultIfBlank(trimmed(getNested(project, "settings", "buildType")), "gradle"));
		javaRuntime.put("javaVersion", javaVersion);
		javaRuntime.put("enableOpenapi", asBoolean(getNested(project, "preferences", "enableOpenAPI")));
		javaRuntime.put("enableActuator", asBoolean(getNested(project, "preferences", "enableActuator")));
		Object enableLombokRaw = getNested(project, "preferences", "enableLombok");
		javaRuntime.put("enableLombok", enableLombokRaw == null
				? asBoolean(getNested(project, "preferences", "optionalLombok"))
				: asBoolean(enableLombokRaw));
		javaRuntime.put("packageStructure",
				defaultIfBlank(trimmed(getNested(project, "preferences", "packages")), "technical"));
		runtime.put("java", javaRuntime);

		Map<String, Object> nodeRuntime = linkedMap();
		nodeRuntime.put("packageName", artifactId);
		nodeRuntime.put("packageManager", defaultIfBlank(trimmed(getNested(project, "settings", "packageManager")), "npm"));
		nodeRuntime.put("port", toInt(getNested(project, "settings", "serverPort"), 3000));
		nodeRuntime.put("framework", "express");
		nodeRuntime.put("orm", "NONE".equals(databaseCode) ? "none" : "prisma");
		nodeRuntime.put("docker", asBoolean(getNested(project, "preferences", "useDockerCompose")));
		runtime.put("node", nodeRuntime);

		Map<String, Object> pythonRuntime = linkedMap();
		pythonRuntime.put("packageName", toSnakeCase(artifactId));
		pythonRuntime.put("framework", "fastapi");
		pythonRuntime.put("orm", "NONE".equals(databaseCode) ? "none" : "sqlalchemy");
		pythonRuntime.put("migrations", "NONE".equals(databaseCode) ? "none" : "alembic");
		pythonRuntime.put("entrypoint", "app/main.py");
		runtime.put("python", pythonRuntime);

		return runtime;
	}

	public String buildYaml(Map<String, Object> project) {
		return JsonYamlConverterUtil.mapToYaml(buildSpec(project));
	}

	private List<Map<String, Object>> mapModels(List<Object> entities, List<Object> relations, Map<String, String> entityToSpecName) {
		List<Map<String, Object>> models = new ArrayList<>();
		for (Object entityRaw : entities) {
			Map<String, Object> entity = asMap(entityRaw);
			List<Object> fields = asList(entity.get("fields"));
			Map<String, Object> idField = null;
			List<Object> nonIdFields = new ArrayList<>();
			for (Object fieldRaw : fields) {
				Map<String, Object> field = asMap(fieldRaw);
				if (asBoolean(field.get("primaryKey"))) {
					idField = field;
				} else {
					nonIdFields.add(field);
				}
			}

			List<Map<String, Object>> modelRelations = new ArrayList<>();
			String entityName = trimmed(entity.get("name"));
			for (Object relationRaw : relations) {
				Map<String, Object> relation = asMap(relationRaw);
				if (trimmed(relation.get("sourceEntity")).equals(entityName)) {
					modelRelations.add(mapRelation(relation));
				}
			}

			Map<String, Object> model = linkedMap();
			model.put("name", entityName.isBlank() ? "Entity" : entityName);
			model.put("tableName", toSnakeCase(entityName.isBlank() ? "entity" : entityName));
			model.put("addRestEndpoints", asBoolean(entity.get("addRestEndpoints")));
			model.put("addCrudOperations", asBoolean(entity.get("addCrudOperations")));
			model.put("classMethods", mapClassMethods(entity.get("classMethods")));

			Map<String, Object> options = linkedMap();
			options.put("entity", !asBoolean(entity.get("mappedSuperclass")));
			options.put("immutable", asBoolean(entity.get("immutable")));
			options.put("auditing", asBoolean(entity.get("auditable")));
			options.put("softDelete", asBoolean(entity.get("softDelete")));
			options.put("naturalIdCache", asBoolean(entity.get("naturalIdCache")));
			model.put("options", options);
			model.put("id", mapId(idField));

			List<Map<String, Object>> mappedFields = new ArrayList<>();
			for (Object field : nonIdFields) {
				mappedFields.add(mapModelField(asMap(field)));
			}
			model.put("fields", mappedFields);

			String mappedSpecName = entityToSpecName.get(entityName);
			if (mappedSpecName != null && !mappedSpecName.isBlank()) {
				model.put("rest-spec-name", mappedSpecName);
			}

			Map<String, Object> restConfig = mapRestConfig(asMap(entity.get("restConfig")));
			if (restConfig != null) {
				model.put("rest", restConfig);
			}
			if (!modelRelations.isEmpty()) {
				model.put("relations", modelRelations);
			}

			models.add(model);
		}
		return models;
	}

	private RestSpecSection buildRestSpecSection(List<Object> entities, Map<String, Object> controllersConfig, boolean includeControllers) {
		List<Map<String, Object>> specs = new ArrayList<>();
		Map<String, String> entityToSpecName = new LinkedHashMap<>();
		Map<String, Integer> specIndexByName = new LinkedHashMap<>();

		for (Object entityRaw : entities) {
			Map<String, Object> entity = asMap(entityRaw);
			if (!asBoolean(entity.get("addRestEndpoints"))) {
				continue;
			}
			Map<String, Object> mapped = mapRestConfig(asMap(entity.get("restConfig")));
			if (mapped == null) {
				continue;
			}
			String entityName = trimmed(entity.get("name"));
			String specName = addOrUpdateSpec(specs, specIndexByName,
					defaultIfBlank(trimmed(mapped.get("resourceName")), entityName.isBlank() ? "EntityRest" : entityName), mapped);
			if (!entityName.isBlank()) {
				entityToSpecName.put(entityName, specName);
			}
		}

		if (includeControllers) {
			Map<String, Object> mappedControllers = mapRestConfig(controllersConfig);
			if (mappedControllers != null) {
				addOrUpdateSpec(specs, specIndexByName,
						defaultIfBlank(trimmed(mappedControllers.get("resourceName")), "ControllersRest"),
						mappedControllers);
			}
		}

		return new RestSpecSection(specs, entityToSpecName);
	}

	private String addOrUpdateSpec(List<Map<String, Object>> specs, Map<String, Integer> specIndexByName, String name,
			Map<String, Object> config) {
		String specName = defaultIfBlank(trimmed(name), "RestSpec");
		Map<String, Object> spec = linkedMap();
		spec.put("name", specName);
		spec.putAll(config);
		Integer existingIndex = specIndexByName.get(specName);
		if (existingIndex == null) {
			specIndexByName.put(specName, specs.size());
			specs.add(spec);
		} else {
			specs.set(existingIndex, spec);
		}
		return specName;
	}

	private boolean hasNamedControllersConfig(Map<String, Object> config) {
		return !trimmed(config.get("resourceName")).isBlank();
	}

	private Map<String, Object> mapRestConfig(Map<String, Object> restConfig) {
		if (restConfig.isEmpty()) {
			return null;
		}
		List<String> operations = List.of("list", "get", "create", "patch", "delete", "bulkInsert", "bulkUpdate", "bulkDelete");
		Map<String, Object> methods = linkedMap();
		for (String key : operations) {
			if (!asBoolean(getNested(restConfig, "methods", key))) {
				continue;
			}
			Map<String, Object> method = linkedMap();
			method.put("request", buildOperationRequestConfig(key, restConfig));
			method.put("response", buildOperationResponseConfig(restConfig, key));
			Map<String, Object> documentation = buildOperationDocumentationConfig(restConfig, key);
			if (documentation != null) {
				method.put("documentation", documentation);
			}
			methods.put(key, method);
		}

		Map<String, Object> mapped = linkedMap();
		mapped.put("resourceName", trimmed(restConfig.get("resourceName")));
		mapped.put("basePath", trimmed(restConfig.get("basePath")));

		Map<String, Object> apiVersioning = linkedMap();
		apiVersioning.put("enabled", asBoolean(getNested(restConfig, "apiVersioning", "enabled")));
		apiVersioning.put("strategy", "path".equals(trimmed(getNested(restConfig, "apiVersioning", "strategy"))) ? "path" : "header");
		apiVersioning.put("headerName", trimmed(getNested(restConfig, "apiVersioning", "headerName")));
		apiVersioning.put("defaultVersion", trimmed(getNested(restConfig, "apiVersioning", "defaultVersion")));
		mapped.put("apiVersioning", apiVersioning);

		String pathVariableType = String.valueOf(restConfig.getOrDefault("pathVariableType", "UUID"));
		mapped.put("pathVariableType", List.of("UUID", "LONG", "STRING").contains(pathVariableType) ? pathVariableType : "UUID");

		Map<String, Object> deletion = linkedMap();
		deletion.put("mode", "HARD".equals(restConfigValue(restConfig, "deletion", "mode")) ? "HARD" : "SOFT");
		deletion.put("restoreEndpoint", asBoolean(getNested(restConfig, "deletion", "restoreEndpoint")));
		deletion.put("includeDeletedParam", asBoolean(getNested(restConfig, "deletion", "includeDeletedParam")));
		mapped.put("deletion", deletion);

		Map<String, Object> hateoas = linkedMap();
		hateoas.put("enabled", asBoolean(getNested(restConfig, "hateoas", "enabled")));
		hateoas.put("selfLink", asBoolean(getNested(restConfig, "hateoas", "selfLink")));
		hateoas.put("updateLink", asBoolean(getNested(restConfig, "hateoas", "updateLink")));
		hateoas.put("deleteLink", asBoolean(getNested(restConfig, "hateoas", "deleteLink")));
		mapped.put("hateoas", hateoas);

		Map<String, Object> documentation = linkedMap();
		documentation.put("includeDefaultDocumentation", getNested(restConfig, "documentation", "includeDefaultDocumentation") != Boolean.FALSE);
		mapped.put("documentation", documentation);
		mapped.put("methods", methods);
		return mapped;
	}

	private List<Map<String, Object>> mapDtos(List<Object> dataObjects, boolean useJavaRecordsForDtos) {
		List<Map<String, Object>> result = new ArrayList<>();
		for (Object raw : dataObjects) {
			Map<String, Object> dataObject = asMap(raw);
			Map<String, Object> dto = linkedMap();
			dto.put("name", defaultIfBlank(trimmed(dataObject.get("name")), "DataObject"));
			dto.put("type", defaultIfBlank(trimmed(dataObject.get("dtoType")), "request"));
			List<Map<String, Object>> fields = new ArrayList<>();
			for (Object fieldRaw : asList(dataObject.get("fields"))) {
				fields.add(mapDtoField(asMap(fieldRaw)));
			}
			dto.put("fields", fields);
			if (!useJavaRecordsForDtos) {
				dto.put("classMethods", mapClassMethods(dataObject.get("classMethods")));
			}
			if (asBoolean(dataObject.get("mapperEnabled")) && !asList(dataObject.get("mapperModels")).isEmpty()) {
				Map<String, Object> mapper = linkedMap();
				mapper.put("enabled", true);
				mapper.put("models", asStringList(dataObject.get("mapperModels")));
				dto.put("mapper", mapper);
			}
			result.add(dto);
		}
		return result;
	}

	private List<Map<String, Object>> mapEnums(List<Object> enums) {
		List<Map<String, Object>> result = new ArrayList<>();
		for (Object raw : enums) {
			Map<String, Object> enumItem = asMap(raw);
			String name = trimmed(enumItem.get("name"));
			List<String> constants = asStringList(enumItem.get("constants"));
			if (name.isBlank() || constants.isEmpty()) {
				continue;
			}
			Map<String, Object> mapped = linkedMap();
			mapped.put("name", name);
			mapped.put("storage", defaultIfBlank(trimmed(enumItem.get("storage")), "STRING"));
			mapped.put("constants", constants);
			result.add(mapped);
		}
		return result;
	}

	private List<Map<String, Object>> mapMappers(List<Object> mappers) {
		List<Map<String, Object>> result = new ArrayList<>();
		for (Object raw : mappers) {
			Map<String, Object> mapper = asMap(raw);
			String name = trimmed(mapper.get("name"));
			String fromModel = trimmed(mapper.get("fromModel"));
			String toModel = trimmed(mapper.get("toModel"));
			List<Map<String, Object>> mappings = new ArrayList<>();
			for (Object mappingRaw : asList(mapper.get("mappings"))) {
				Map<String, Object> item = asMap(mappingRaw);
				String sourceField = trimmed(item.get("sourceField"));
				String targetField = trimmed(item.get("targetField"));
				if (sourceField.isBlank() || targetField.isBlank()) {
					continue;
				}
				Map<String, Object> mappedItem = linkedMap();
				mappedItem.put("sourceField", sourceField);
				mappedItem.put("targetField", targetField);
				mappings.add(mappedItem);
			}
			if (!name.isBlank() && !fromModel.isBlank() && !toModel.isBlank() && !mappings.isEmpty()) {
				Map<String, Object> mapped = linkedMap();
				mapped.put("name", name);
				mapped.put("fromModel", fromModel);
				mapped.put("toModel", toModel);
				mapped.put("mappings", mappings);
				result.add(mapped);
			}
		}
		return result;
	}

	private List<Map<String, Object>> mapAutoRequestMappers(List<Object> entities, List<Object> dataObjects) {
		Map<String, Map<String, Object>> dtoByName = new LinkedHashMap<>();
		for (Object dtoRaw : dataObjects) {
			Map<String, Object> dto = asMap(dtoRaw);
			String name = trimmed(dto.get("name"));
			if (!name.isBlank()) {
				dtoByName.put(name.toLowerCase(Locale.ROOT), dto);
			}
		}

		List<Map<String, Object>> autoMappers = new ArrayList<>();
		Set<String> seen = new LinkedHashSet<>();
		for (Object entityRaw : entities) {
			Map<String, Object> entity = asMap(entityRaw);
			String entityName = trimmed(entity.get("name"));
			if (entityName.isBlank() || !asBoolean(entity.get("addRestEndpoints")) || !asBoolean(getNested(entity, "restConfig", "mapToEntity"))) {
				continue;
			}
			Map<String, Object> restConfig = getNestedMap(entity, "restConfig");
			Map<String, Object> requestConfig = getNestedMap(restConfig, "requestResponse", "request");
			List<String> candidateDtos = List.of(
					extractDtoType(getNested(requestConfig, "create", "dtoName")),
					extractDtoType(getNested(requestConfig, "update", "dtoName")),
					extractDtoType(getNested(requestConfig, "patch", "dtoName")),
					extractDtoType(getNested(requestConfig, "list", "dtoName")),
					extractDtoType(requestConfig.get("bulkInsertType")),
					extractDtoType(requestConfig.get("bulkUpdateType")));
			for (String dtoName : new LinkedHashSet<>(candidateDtos)) {
				if (dtoName == null || dtoName.isBlank() || dtoName.equalsIgnoreCase(entityName)) {
					continue;
				}
				Map<String, Object> dto = dtoByName.get(dtoName.toLowerCase(Locale.ROOT));
				if (dto == null) {
					continue;
				}
				String mapperName = dtoName + "RequestMapper";
				String key = mapperName.toLowerCase(Locale.ROOT) + "::" + dtoName.toLowerCase(Locale.ROOT) + "::"
						+ entityName.toLowerCase(Locale.ROOT);
				if (!seen.add(key)) {
					continue;
				}
				Map<String, Object> mapper = linkedMap();
				mapper.put("name", mapperName);
				mapper.put("fromModel", dtoName);
				mapper.put("toModel", entityName);
				mapper.put("mappings", buildSameNameMappings(asList(dto.get("fields")), asList(entity.get("fields"))));
				autoMappers.add(mapper);
			}
		}
		return autoMappers;
	}

	private List<Map<String, Object>> mergeMapperSpecs(List<Map<String, Object>> manualMappers, List<Map<String, Object>> autoMappers) {
		List<Map<String, Object>> merged = new ArrayList<>();
		Set<String> seenNames = new LinkedHashSet<>();
		for (Map<String, Object> mapper : manualMappers) {
			String name = trimmed(mapper.get("name"));
			if (name.isBlank()) {
				continue;
			}
			seenNames.add(name.toLowerCase(Locale.ROOT));
			merged.add(mapper);
		}
		for (Map<String, Object> mapper : autoMappers) {
			String name = trimmed(mapper.get("name"));
			if (name.isBlank() || seenNames.contains(name.toLowerCase(Locale.ROOT))) {
				continue;
			}
			seenNames.add(name.toLowerCase(Locale.ROOT));
			merged.add(mapper);
		}
		return merged;
	}

	private String extractDtoType(Object rawType) {
		String value = trimmed(rawType);
		if (value.isBlank()) {
			return "";
		}
		if (value.startsWith("List<") && value.endsWith(">")) {
			return trimmed(value.substring(5, value.length() - 1));
		}
		return value;
	}

	private List<Map<String, Object>> buildSameNameMappings(List<Object> sourceFields, List<Object> targetFields) {
		Map<String, String> targetNamesByLower = new LinkedHashMap<>();
		for (Object fieldRaw : targetFields) {
			String name = trimmed(asMap(fieldRaw).get("name"));
			if (!name.isBlank()) {
				targetNamesByLower.put(name.toLowerCase(Locale.ROOT), name);
			}
		}
		List<Map<String, Object>> result = new ArrayList<>();
		for (Object fieldRaw : sourceFields) {
			String sourceName = trimmed(asMap(fieldRaw).get("name"));
			if (sourceName.isBlank()) {
				continue;
			}
			String targetName = targetNamesByLower.get(sourceName.toLowerCase(Locale.ROOT));
			if (targetName == null) {
				continue;
			}
			Map<String, Object> mapping = linkedMap();
			mapping.put("sourceField", sourceName);
			mapping.put("targetField", targetName);
			result.add(mapping);
		}
		return result;
	}

	private List<String> extractDependencies(String dependenciesString, List<String> selectedDependencies) {
		LinkedHashSet<String> all = new LinkedHashSet<>();
		for (String item : String.valueOf(dependenciesString == null ? "" : dependenciesString).split(",")) {
			String trimmedItem = item.trim();
			if (!trimmedItem.isEmpty()) {
				all.add(trimmedItem);
			}
		}
		for (String item : selectedDependencies) {
			String trimmedItem = item.trim();
			if (!trimmedItem.isEmpty()) {
				all.add(trimmedItem);
			}
		}
		return new ArrayList<>(all);
	}

	private List<String> mapProfiles(Object profiles) {
		if (!(profiles instanceof List<?> profileList)) {
			return new ArrayList<>();
		}
		LinkedHashSet<String> normalized = new LinkedHashSet<>();
		for (Object profile : profileList) {
			String normalizedProfile = normalizeProfileName(profile);
			if (normalizedProfile != null && isValidProfileName(normalizedProfile)) {
				normalized.add(normalizedProfile);
			}
		}
		return new ArrayList<>(normalized);
	}

	private List<String> getActuatorConfigurationOptions(Object profileSource) {
		List<String> normalizedProfiles = new ArrayList<>();
		for (String profile : mapProfiles(profileSource)) {
			if (!"default".equals(profile)) {
				normalizedProfiles.add(profile);
			}
		}
		List<String> result = new ArrayList<>();
		result.add("default");
		result.addAll(normalizedProfiles);
		return result;
	}

	private List<String> sanitizeActuatorEndpoints(Object rawEndpoints) {
		if (!(rawEndpoints instanceof List<?> endpoints)) {
			return new ArrayList<>(DEFAULT_ACTUATOR_ENDPOINTS);
		}
		LinkedHashSet<String> cleaned = new LinkedHashSet<>();
		for (Object endpoint : endpoints) {
			String item = String.valueOf(endpoint == null ? "" : endpoint).trim().toLowerCase(Locale.ROOT);
			if (!item.isEmpty() && ACTUATOR_ENDPOINT_OPTIONS.contains(item)) {
				cleaned.add(item);
			}
		}
		return cleaned.isEmpty() ? new ArrayList<>(DEFAULT_ACTUATOR_ENDPOINTS) : new ArrayList<>(cleaned);
	}

	private Map<String, List<String>> sanitizeActuatorConfigurations(Object rawConfigurations, List<String> availableConfigurations) {
		Set<String> allowedConfigurations = new LinkedHashSet<>(availableConfigurations);
		Map<String, List<String>> sanitized = new LinkedHashMap<>();
		sanitized.put("default", new ArrayList<>(DEFAULT_ACTUATOR_ENDPOINTS));
		if (rawConfigurations instanceof List<?>) {
			sanitized.put("default", sanitizeActuatorEndpoints(rawConfigurations));
			return sanitized;
		}
		if (!(rawConfigurations instanceof Map<?, ?> configurations)) {
			return sanitized;
		}
		for (Map.Entry<?, ?> entry : configurations.entrySet()) {
			String key = normalizeProfileName(entry.getKey());
			if (key == null || !allowedConfigurations.contains(key)) {
				continue;
			}
			Object value = entry.getValue();
			Object include = value instanceof Map<?, ?> valueMap
					? nonNull(getNested(asMap(valueMap), "endpoints", "include"), valueMap.get("include"))
					: value;
			sanitized.put(key, sanitizeActuatorEndpoints(include));
		}
		if (!sanitized.containsKey("default") || sanitized.get("default").isEmpty()) {
			sanitized.put("default", new ArrayList<>(DEFAULT_ACTUATOR_ENDPOINTS));
		}
		return sanitized;
	}

	private Map<String, Object> buildOperationResponseConfig(Map<String, Object> restConfig, String operationKey) {
		String responseType = "RESPONSE_ENTITY";
		String configuredResponseType = trimmed(getNested(restConfig, "requestResponse", "response", "responseType"));
		if ("DTO_DIRECT".equals(configuredResponseType)) {
			responseType = "DTO_DIRECT";
		} else if ("CUSTOM_WRAPPER".equals(configuredResponseType)) {
			responseType = "CUSTOM_WRAPPER";
		}
		String perOperationDto = trimmed(getNested(restConfig, "requestResponse", "response", "endpointDtos", operationKey));
		String defaultCustomWrapperDto = getDefaultCustomWrapperDto(restConfig, operationKey);

		Map<String, Object> response = linkedMap();
		response.put("responseType", responseType);
		if ("CUSTOM_WRAPPER".equals(responseType)) {
			response.put("dtoName", defaultIfBlank(perOperationDto,
					defaultIfBlank(trimmed(getNested(restConfig, "requestResponse", "response", "dtoName")), defaultCustomWrapperDto)));
		} else {
			response.put("dtoName", trimmed(getNested(restConfig, "requestResponse", "response", "dtoName")));
		}
		String responseWrapper = trimmed(getNested(restConfig, "requestResponse", "response", "responseWrapper"));
		if ("NONE".equals(responseWrapper)) {
			response.put("responseWrapper", "NONE");
		} else if ("UPSERT".equals(responseWrapper)) {
			response.put("responseWrapper", "UPSERT");
		} else {
			response.put("responseWrapper", "STANDARD_ENVELOPE");
		}
		response.put("enableFieldProjection", asBoolean(getNested(restConfig, "requestResponse", "response", "enableFieldProjection")));
		response.put("includeHateoasLinks", asBoolean(getNested(restConfig, "requestResponse", "response", "includeHateoasLinks")));
		return response;
	}

	private Map<String, Object> buildOperationDocumentationConfig(Map<String, Object> restConfig, String docKey) {
		boolean includeDefaults = getNested(restConfig, "documentation", "includeDefaultDocumentation") != Boolean.FALSE;
		DefaultDocumentation defaultDocumentation = getDefaultDocumentationForOperation(docKey, trimmed(restConfig.get("resourceName")));
		String description = defaultIfBlank(trimmed(getNested(restConfig, "documentation", "endpoints", docKey, "description")),
				includeDefaults ? defaultDocumentation.description : "");
		String group = defaultIfBlank(trimmed(getNested(restConfig, "documentation", "endpoints", docKey, "group")),
				includeDefaults ? defaultDocumentation.group : "");
		List<String> descriptionTags = asStringList(getNested(restConfig, "documentation", "endpoints", docKey, "descriptionTags"));
		List<String> resolvedDescriptionTags = !descriptionTags.isEmpty()
				? descriptionTags
				: (includeDefaults ? defaultDocumentation.descriptionTags : List.of());
		boolean deprecated = asBoolean(getNested(restConfig, "documentation", "endpoints", docKey, "deprecated"));

		Map<String, Object> documentation = linkedMap();
		if (!description.isBlank()) {
			documentation.put("description", description);
		}
		if (!group.isBlank()) {
			documentation.put("group", group);
		}
		if (!resolvedDescriptionTags.isEmpty()) {
			documentation.put("descriptionTags", resolvedDescriptionTags);
		}
		if (deprecated) {
			documentation.put("deprecated", true);
		}
		return documentation.isEmpty() ? null : documentation;
	}

	private DefaultDocumentation getDefaultDocumentationForOperation(String operationKey, String resourceName) {
		Map<String, String> endpointLabel = Map.of(
				"list", "List",
				"get", "Get By Key",
				"create", "Create",
				"update", "Update",
				"patch", "Patch",
				"delete", "Delete",
				"bulkInsert", "Bulk Insert",
				"bulkUpdate", "Bulk Update",
				"bulkDelete", "Bulk Delete");
		String target = resourceName.isBlank() ? "API" : resourceName;
		return new DefaultDocumentation(
				(endpointLabel.getOrDefault(operationKey, operationKey) + " operation for " + target),
				target + " Group",
				List.of(operationKey));
	}

	private Map<String, Object> buildOperationRequestConfig(String operationKey, Map<String, Object> restConfig) {
		String mappedEntityName = trimmed(restConfig.get("mappedEntityName"));
		String keyTypeFromSettings = resolveConfiguredKeyType(restConfig);
		switch (operationKey) {
			case "create":
				return mapOf(
						"mode", "NONE".equals(restConfigValue(restConfig, "requestResponse", "request", "create", "mode")) ? "NONE" : "GENERATE_DTO",
						"dtoName", defaultIfBlank(normalizeRequestDtoName(getNested(restConfig, "requestResponse", "request", "create", "dtoName")), mappedEntityName));
			case "update":
				return mapOf(
						"mode", "NONE".equals(restConfigValue(restConfig, "requestResponse", "request", "update", "mode")) ? "NONE" : "GENERATE_DTO",
						"dtoName", defaultIfBlank(normalizeRequestDtoName(getNested(restConfig, "requestResponse", "request", "update", "dtoName")), mappedEntityName));
			case "patch":
				return mapOf(
						"mode", "GENERATE_DTO",
						"dtoName", defaultIfBlank(normalizeRequestDtoName(getNested(restConfig, "requestResponse", "request", "patch", "dtoName")),
								defaultIfBlank(normalizeRequestDtoName(getNested(restConfig, "requestResponse", "request", "create", "dtoName")), mappedEntityName)));
			case "list": {
				Map<String, Object> pagination = linkedMap();
				pagination.put("enabled", getNested(restConfig, "pagination", "enabled") == null
						? asBoolean(restConfig.get("pagination"))
						: asBoolean(getNested(restConfig, "pagination", "enabled")));
				pagination.put("mode", "CURSOR".equals(restConfigValue(restConfig, "pagination", "mode")) ? "CURSOR" : "OFFSET");
				pagination.put("sortField", trimmed(getNested(restConfig, "pagination", "sortField")));
				pagination.put("sortDirection", "ASC".equals(restConfigValue(restConfig, "pagination", "sortDirection")) ? "ASC" : "DESC");
				Map<String, Object> searchFiltering = linkedMap();
				searchFiltering.put("keywordSearch", asBoolean(getNested(restConfig, "searchFiltering", "keywordSearch")));
				searchFiltering.put("jpaSpecification", asBoolean(getNested(restConfig, "searchFiltering", "jpaSpecification")));
				searchFiltering.put("searchableFields", asStringList(getNested(restConfig, "searchFiltering", "searchableFields")));
				Map<String, Object> result = linkedMap();
				result.put("mode", "NONE".equals(restConfigValue(restConfig, "requestResponse", "request", "list", "mode")) ? "NONE" : "GENERATE_DTO");
				result.put("dtoName", defaultIfBlank(normalizeRequestDtoName(getNested(restConfig, "requestResponse", "request", "list", "dtoName")), mappedEntityName));
				result.put("pagination", pagination);
				result.put("searchFiltering", searchFiltering);
				return result;
			}
			case "get":
				return mapOf("idType", keyTypeFromSettings);
			case "delete":
				return mapOf(
						"mode", "NONE".equals(restConfigValue(restConfig, "requestResponse", "request", "delete", "mode")) ? "NONE" : "GENERATE_DTO",
						"dtoName", trimmed(getNested(restConfig, "requestResponse", "request", "delete", "dtoName")),
						"idType", keyTypeFromSettings);
			case "bulkInsert": {
				String createDto = defaultIfBlank(normalizeRequestDtoName(getNested(restConfig, "requestResponse", "request", "create", "dtoName")), mappedEntityName);
				String derivedType = createDto.isBlank() ? "" : ("List<" + createDto + ">");
				Map<String, Object> batch = mapOf(
						"batchSize", toInt(getNested(restConfig, "batchOperations", "insert", "batchSize"), 1),
						"enableAsyncMode", asBoolean(getNested(restConfig, "batchOperations", "insert", "enableAsyncMode")));
				return mapOf("type", derivedType, "batch", batch);
			}
			case "bulkUpdate": {
				String createDto = defaultIfBlank(normalizeRequestDtoName(getNested(restConfig, "requestResponse", "request", "create", "dtoName")), mappedEntityName);
				String derivedType = createDto.isBlank() ? "" : ("List<" + createDto + ">");
				Map<String, Object> batch = linkedMap();
				batch.put("batchSize", toInt(getNested(restConfig, "batchOperations", "update", "batchSize"), 1));
				batch.put("updateMode", "PATCH".equals(restConfigValue(restConfig, "batchOperations", "update", "updateMode")) ? "PATCH" : "PUT");
				batch.put("optimisticLockHandling",
						"SKIP_CONFLICTS".equals(restConfigValue(restConfig, "batchOperations", "update", "optimisticLockHandling"))
								? "SKIP_CONFLICTS" : "FAIL_ON_CONFLICT");
				batch.put("validationStrategy",
						"SKIP_DUPLICATES".equals(restConfigValue(restConfig, "batchOperations", "update", "validationStrategy"))
								? "SKIP_DUPLICATES" : "VALIDATE_ALL_FIRST");
				batch.put("enableAsyncMode", asBoolean(getNested(restConfig, "batchOperations", "update", "enableAsyncMode")));
				batch.put("asyncProcessing", asBoolean(getNested(restConfig, "batchOperations", "update", "asyncProcessing")));
				return mapOf("type", derivedType, "batch", batch);
			}
			case "bulkDelete": {
				String deleteDto = trimmed(getNested(restConfig, "requestResponse", "request", "delete", "dtoName"));
				String deleteIdType = keyTypeFromSettings;
				String derivedType = !deleteDto.isBlank() ? ("List<" + deleteDto + ">")
						: (!deleteIdType.isBlank() ? ("List<" + deleteIdType + ">") : "");
				Map<String, Object> batch = linkedMap();
				batch.put("deletionStrategy",
						"HARD".equals(restConfigValue(restConfig, "batchOperations", "bulkDelete", "deletionStrategy")) ? "HARD" : "SOFT");
				batch.put("batchSize", toInt(getNested(restConfig, "batchOperations", "bulkDelete", "batchSize"), 1));
				batch.put("failureStrategy",
						"CONTINUE_AND_REPORT_FAILURES".equals(restConfigValue(restConfig, "batchOperations", "bulkDelete", "failureStrategy"))
								? "CONTINUE_AND_REPORT_FAILURES" : "STOP_ON_FIRST_ERROR");
				batch.put("enableAsyncMode", asBoolean(getNested(restConfig, "batchOperations", "bulkDelete", "enableAsyncMode")));
				batch.put("allowIncludeDeletedParam", asBoolean(getNested(restConfig, "batchOperations", "bulkDelete", "allowIncludeDeletedParam")));
				return mapOf("type", derivedType, "batch", batch);
			}
			default:
				return linkedMap();
		}
	}

	private String normalizeRequestDtoName(Object value) {
		String candidate = trimmed(value);
		if ("Request".equals(candidate) || "UpdateRequest".equals(candidate)) {
			return "";
		}
		return candidate;
	}

	private String getDefaultCustomWrapperDto(Map<String, Object> restConfig, String operationKey) {
		String idType = resolveConfiguredKeyType(restConfig);
		String entityName = defaultIfBlank(trimmed(restConfig.get("mappedEntityName")), trimmed(restConfig.get("resourceName")));
		return switch (operationKey) {
			case "create", "delete" -> idType;
			case "get", "patch", "update" -> entityName;
			case "list", "bulkUpdate" -> entityName.isBlank() ? "" : ("List<" + entityName + ">");
			case "bulkInsert", "bulkDelete" -> "List<" + idType + ">";
			default -> "";
		};
	}

	private String resolveConfiguredKeyType(Map<String, Object> restConfig) {
		String raw = trimmed(restConfig.get("pathVariableType")).toUpperCase(Locale.ROOT);
		if ("LONG".equals(raw)) {
			return "Long";
		}
		if ("STRING".equals(raw)) {
			return "String";
		}
		return "UUID";
	}

	private Map<String, Object> mapModelField(Map<String, Object> field) {
		Map<String, Object> mapped = linkedMap();
		mapped.put("name", defaultIfBlank(trimmed(field.get("name")), "field"));
		String normalizedType = normalizeType(field.get("type"));
		mapped.put("type", normalizedType);

		List<Object> constraints = mapConstraints(field.get("constraints"));
		if (!constraints.isEmpty()) {
			mapped.put("constraints", constraints);
		}

		Map<String, Object> column = linkedMap();
		if (!trimmed(field.get("name")).isBlank()) {
			column.put("name", toSnakeCase(trimmed(field.get("name"))));
		}
		if (field.containsKey("required") && field.get("required") instanceof Boolean required) {
			column.put("nullable", !required);
		} else {
			for (Object constraint : constraints) {
				if (isNotNullConstraint(constraint)) {
					column.put("nullable", false);
					break;
				}
			}
		}
		if (field.get("unique") == Boolean.TRUE) {
			column.put("unique", true);
		}
		if ("String".equals(normalizedType) && hasNumber(field.get("maxLength"))) {
			column.put("length", Integer.parseInt(String.valueOf(field.get("maxLength"))));
		}
		if (!column.isEmpty()) {
			mapped.put("column", column);
		}
		return mapped;
	}

	private Map<String, Object> mapDtoField(Map<String, Object> field) {
		Map<String, Object> dtoField = linkedMap();
		dtoField.put("name", defaultIfBlank(trimmed(field.get("name")), "field"));
		dtoField.put("type", normalizeType(field.get("type")));
		String jsonProperty = trimmed(field.get("jsonProperty"));
		if (!jsonProperty.isBlank()) {
			dtoField.put("jsonProperty", jsonProperty);
		}
		List<Object> constraints = mapConstraints(field.get("constraints"));
		if (!constraints.isEmpty()) {
			dtoField.put("constraints", constraints);
		}
		return dtoField;
	}

	private Map<String, Object> mapClassMethods(Object classMethodsRaw) {
		Map<String, Object> classMethods = asMap(classMethodsRaw);
		Map<String, Object> mapped = linkedMap();
		mapped.put("toString", asBoolean(nonNull(classMethods.get("toString"), Boolean.TRUE)));
		mapped.put("hashCode", asBoolean(nonNull(classMethods.get("hashCode"), Boolean.TRUE)));
		mapped.put("equals", asBoolean(nonNull(classMethods.get("equals"), Boolean.TRUE)));
		mapped.put("noArgsConstructor", asBoolean(nonNull(classMethods.get("noArgsConstructor"), Boolean.TRUE)));
		mapped.put("allArgsConstructor", asBoolean(nonNull(classMethods.get("allArgsConstructor"), Boolean.TRUE)));
		mapped.put("builder", asBoolean(nonNull(classMethods.get("builder"), Boolean.FALSE)));
		return mapped;
	}

	private boolean supportsJavaRecords(Object javaVersion) {
		String raw = trimmed(javaVersion);
		if (raw.isBlank()) {
			return true;
		}
		String normalized = raw.startsWith("1.") ? raw.substring(2) : raw;
		Matcher matcher = CONSTRAINT_PARAM_PATTERN.matcher(normalized);
		if (!matcher.find()) {
			return true;
		}
		try {
			return Integer.parseInt(matcher.group()) >= 17;
		} catch (NumberFormatException ex) {
			return true;
		}
	}

	private Map<String, Object> mapRelation(Map<String, Object> relation) {
		String type = defaultIfBlank(trimmed(relation.get("relationType")), "ManyToOne");
		Map<String, Object> mapped = linkedMap();
		mapped.put("name", defaultIfBlank(trimmed(relation.get("sourceFieldName")), "relation"));
		mapped.put("type", type);
		mapped.put("target", defaultIfBlank(trimmed(relation.get("targetEntity")), "Target"));

		List<String> cascade = asStringList(relation.get("cascade"));
		if (!cascade.isEmpty()) {
			mapped.put("cascade", new ArrayList<>(new LinkedHashSet<>(cascade)));
		}
		String mappedBy = trimmed(relation.get("mappedBy"));
		if (!mappedBy.isBlank()) {
			mapped.put("mappedBy", mappedBy);
		}
		if (relation.get("orphanRemoval") == Boolean.TRUE) {
			mapped.put("orphanRemoval", true);
		}
		String orderBy = trimmed(relation.get("orderBy"));
		if (!orderBy.isBlank()) {
			mapped.put("orderBy", orderBy);
		}
		String orderColumnName = trimmed(getNested(relation, "orderColumn", "name"));
		if (!orderColumnName.isBlank()) {
			mapped.put("orderColumn", mapOf("name", orderColumnName));
		}
		if (List.of("ManyToOne", "OneToOne").contains(type)) {
			if (relation.get("optional") instanceof Boolean optional) {
				mapped.put("optional", optional);
			} else if (relation.get("required") instanceof Boolean required) {
				mapped.put("optional", !required);
			}
			Map<String, Object> joinColumn = mapJoinColumn(asMap(relation.get("joinColumn")));
			if (joinColumn != null) {
				mapped.put("joinColumn", joinColumn);
			}
		}
		if ("ManyToMany".equals(type)) {
			Map<String, Object> joinTable = mapJoinTable(asMap(relation.get("joinTable")));
			if (joinTable != null) {
				mapped.put("joinTable", joinTable);
			}
		}
		return mapped;
	}

	private Map<String, Object> mapJoinColumn(Map<String, Object> joinColumn) {
		if (joinColumn.isEmpty()) {
			return null;
		}
		Map<String, Object> mapped = linkedMap();
		String name = trimmed(joinColumn.get("name"));
		String referenced = trimmed(joinColumn.get("referencedColumnName"));
		if (!name.isBlank()) {
			mapped.put("name", name);
		}
		if (!referenced.isBlank()) {
			mapped.put("referencedColumnName", referenced);
		}
		if (joinColumn.get("nullable") instanceof Boolean nullable) {
			mapped.put("nullable", nullable);
		}
		if (joinColumn.get("index") == Boolean.TRUE) {
			mapped.put("index", true);
		}
		String onDelete = trimmed(joinColumn.get("onDelete"));
		if (!onDelete.isBlank()) {
			mapped.put("onDelete", onDelete);
		}
		return mapped.isEmpty() ? null : mapped;
	}

	private Map<String, Object> mapJoinTable(Map<String, Object> joinTable) {
		if (joinTable.isEmpty()) {
			return null;
		}
		Map<String, Object> mapped = linkedMap();
		String name = trimmed(joinTable.get("name"));
		if (!name.isBlank()) {
			mapped.put("name", name);
		}
		List<Map<String, Object>> joinColumns = mapJoinColumns(joinTable.get("joinColumns"));
		if (!joinColumns.isEmpty()) {
			mapped.put("joinColumns", joinColumns);
		}
		List<Map<String, Object>> inverseJoinColumns = mapJoinColumns(joinTable.get("inverseJoinColumns"));
		if (!inverseJoinColumns.isEmpty()) {
			mapped.put("inverseJoinColumns", inverseJoinColumns);
		}
		if (joinTable.get("uniquePair") == Boolean.TRUE) {
			mapped.put("uniquePair", true);
		}
		String onDelete = trimmed(joinTable.get("onDelete"));
		if (!onDelete.isBlank()) {
			mapped.put("onDelete", onDelete);
		}
		return mapped.isEmpty() ? null : mapped;
	}

	private List<Map<String, Object>> mapJoinColumns(Object columnsRaw) {
		List<Map<String, Object>> result = new ArrayList<>();
		for (Object raw : asList(columnsRaw)) {
			Map<String, Object> mapped = mapJoinColumn(asMap(raw));
			if (mapped != null) {
				result.add(mapped);
			}
		}
		return result;
	}

	private List<Object> mapConstraints(Object constraintsRaw) {
		List<Object> result = new ArrayList<>();
		for (Object raw : asList(constraintsRaw)) {
			Object mapped = mapConstraint(asMap(raw));
			if (mapped != null) {
				result.add(mapped);
			}
		}
		return result;
	}

	private Object mapConstraint(Map<String, Object> constraint) {
		String name = trimmed(constraint.get("name"));
		if (name.isBlank()) {
			return null;
		}
		String value = trimmed(constraint.get("value"));
		String value2 = trimmed(constraint.get("value2"));
		Map<String, Object> params = linkedMap();
		switch (name) {
			case "Size":
				if (!value.isBlank()) {
					params.put("min", toNumberIfPossible(value));
				}
				if (!value2.isBlank()) {
					params.put("max", toNumberIfPossible(value2));
				}
				break;
			case "Min":
			case "Max":
				if (!value.isBlank()) {
					params.put("value", toNumberIfPossible(value));
				}
				break;
			case "DecimalMin":
			case "DecimalMax":
				if (!value.isBlank()) {
					params.put("value", value);
				}
				if (!value2.isBlank()) {
					params.put("inclusive", toBooleanIfPossible(value2));
				}
				break;
			case "Digits":
				if (!value.isBlank()) {
					params.put("integer", toNumberIfPossible(value));
				}
				if (!value2.isBlank()) {
					params.put("fraction", toNumberIfPossible(value2));
				}
				break;
			case "Pattern":
				if (!value.isBlank()) {
					params.put("regex", value);
				}
				break;
			default:
				if (!value.isBlank()) {
					params.put("value", toNumberIfPossible(value));
				}
				if (!value2.isBlank()) {
					params.put("value2", toNumberIfPossible(value2));
				}
		}
		if (params.isEmpty()) {
			return name;
		}
		return mapOf(name, params);
	}

	private Map<String, Object> mapId(Map<String, Object> primaryKeyField) {
		if (primaryKeyField == null || primaryKeyField.isEmpty()) {
			return mapOf(
					"field", "id",
					"type", "Long",
					"generation", mapOf("strategy", "IDENTITY"));
		}
		String type = normalizeType(primaryKeyField.get("type"));
		Map<String, Object> generation = "UUID".equals(type)
				? mapOf("strategy", "UUID", "generatorName", "uuid", "hibernateUuidStrategy", "uuid2")
				: mapOf("strategy", "IDENTITY");
		return mapOf(
				"field", defaultIfBlank(trimmed(primaryKeyField.get("name")), "id"),
				"type", type,
				"generation", generation);
	}

	private static final class RestSpecSection {
		private final List<Map<String, Object>> specs;
		private final Map<String, String> entityToSpecName;

		private RestSpecSection(List<Map<String, Object>> specs, Map<String, String> entityToSpecName) {
			this.specs = specs;
			this.entityToSpecName = entityToSpecName;
		}
	}

	private static final class DefaultDocumentation {
		private final String description;
		private final String group;
		private final List<String> descriptionTags;

		private DefaultDocumentation(String description, String group, List<String> descriptionTags) {
			this.description = description;
			this.group = group;
			this.descriptionTags = descriptionTags;
		}
	}

	private Map<String, Object> linkedMap() {
		return new LinkedHashMap<>();
	}

	private Map<String, Object> mapOf(Object... items) {
		Map<String, Object> result = linkedMap();
		for (int i = 0; i + 1 < items.length; i += 2) {
			result.put(String.valueOf(items[i]), items[i + 1]);
		}
		return result;
	}

	private Object getNested(Map<String, Object> map, Object... keys) {
		Object current = map;
		for (Object key : keys) {
			if (!(current instanceof Map<?, ?> currentMap)) {
				return null;
			}
			current = currentMap.get(key);
		}
		return current;
	}

	private Map<String, Object> getNestedMap(Map<String, Object> map, Object... keys) {
		return asMap(getNested(map, keys));
	}

	private List<Object> getNestedList(Map<String, Object> map, Object... keys) {
		return asList(getNested(map, keys));
	}

	@SuppressWarnings("unchecked")
	private Map<String, Object> asMap(Object value) {
		if (value instanceof Map<?, ?> map) {
			Map<String, Object> result = new LinkedHashMap<>();
			for (Map.Entry<?, ?> entry : map.entrySet()) {
				result.put(String.valueOf(entry.getKey()), entry.getValue());
			}
			return result;
		}
		return new LinkedHashMap<>();
	}

	private List<Object> asList(Object value) {
		if (value instanceof List<?> list) {
			return new ArrayList<>(list);
		}
		return new ArrayList<>();
	}

	private List<String> asStringList(Object value) {
		LinkedHashSet<String> result = new LinkedHashSet<>();
		for (Object item : asList(value)) {
			String text = trimmed(item);
			if (!text.isBlank()) {
				result.add(text);
			}
		}
		return new ArrayList<>(result);
	}

	private String trimmed(Object value) {
		return value == null ? "" : String.valueOf(value).trim();
	}

	private boolean hasNumber(Object value) {
		if (value == null) {
			return false;
		}
		try {
			Double.parseDouble(String.valueOf(value));
			return true;
		} catch (NumberFormatException ex) {
			return false;
		}
	}

	private Object toNumberIfPossible(String value) {
		try {
			double numeric = Double.parseDouble(value);
			if (numeric == Math.rint(numeric)) {
				long asLong = (long) numeric;
				if (asLong <= Integer.MAX_VALUE && asLong >= Integer.MIN_VALUE) {
					return (int) asLong;
				}
				return asLong;
			}
			return numeric;
		} catch (NumberFormatException ex) {
			return value;
		}
	}

	private Object toBooleanIfPossible(String value) {
		String normalized = value.toLowerCase(Locale.ROOT);
		if ("true".equals(normalized)) {
			return true;
		}
		if ("false".equals(normalized)) {
			return false;
		}
		return value;
	}

	private String normalizeType(Object type) {
		String value = trimmed(type);
		Map<String, String> typeMap = Map.of(
				"Int", "Integer",
				"Decimal", "BigDecimal",
				"Date", "LocalDate",
				"Time", "LocalTime",
				"DateTime", "OffsetDateTime",
				"Json", "String");
		return typeMap.getOrDefault(value, value.isBlank() ? "String" : value);
	}

	private String toSnakeCase(String value) {
		return value
				.replaceAll("([a-z0-9])([A-Z])", "$1_$2")
				.replaceAll("[\\s\\-]+", "_")
				.replaceAll("__+", "_")
				.toLowerCase(Locale.ROOT);
	}

	private String toArtifactId(String value) {
		return value.trim()
				.replaceAll("([a-z0-9])([A-Z])", "$1-$2")
				.replaceAll("[\\s_]+", "-")
				.replaceAll("-+", "-")
				.toLowerCase(Locale.ROOT);
	}

	private String toDatabaseCode(Object value) {
		String raw = trimmed(value);
		String normalized = raw.toLowerCase(Locale.ROOT);
		List<String> known = Arrays.asList("NONE", "OTHER", "MSSQL", "MYSQL", "MARIADB", "ORACLE", "POSTGRES", "MONGODB", "DERBY", "H2", "HSQL");
		if (known.contains(raw.toUpperCase(Locale.ROOT))) {
			return raw.toUpperCase(Locale.ROOT);
		}
		return switch (normalized) {
			case "none" -> "NONE";
			case "other" -> "OTHER";
			case "mssql", "mssql server", "sql server" -> "MSSQL";
			case "mysql" -> "MYSQL";
			case "mariadb" -> "MARIADB";
			case "oracle" -> "ORACLE";
			case "postgres", "postgresql" -> "POSTGRES";
			case "mongodb", "mongo" -> "MONGODB";
			case "derby", "apache derby" -> "DERBY";
			case "h2", "h2 database" -> "H2";
			case "hsql", "hypersql", "hsql database" -> "HSQL";
			default -> "POSTGRES";
		};
	}

	private String resolveDatabaseType(Object type, Object databaseCode) {
		String normalizedType = trimmed(type).toUpperCase(Locale.ROOT);
		if ("NONE".equals(normalizedType)) {
			return "NONE";
		}
		if ("NOSQL".equals(normalizedType)) {
			return "NOSQL";
		}
		if ("SQL".equals(normalizedType)) {
			return "SQL";
		}
		String normalizedDb = toDatabaseCode(databaseCode);
		if ("NONE".equals(normalizedDb)) {
			return "NONE";
		}
		if ("MONGODB".equals(normalizedDb)) {
			return "NOSQL";
		}
		return "SQL";
	}

	private String normalizeProfileName(Object value) {
		if (value == null) {
			return null;
		}
		String text = String.valueOf(value).trim();
		return text.isEmpty() ? null : text.toLowerCase(Locale.ROOT);
	}

	private boolean isValidProfileName(String profile) {
		return profile.matches("^[a-z0-9._-]+$");
	}

	private boolean isNotNullConstraint(Object constraint) {
		if (constraint instanceof String text) {
			return "NotNull".equals(text);
		}
		if (!(constraint instanceof Map<?, ?> map) || map.isEmpty()) {
			return false;
		}
		Object firstKey = map.keySet().iterator().next();
		return Objects.equals(firstKey, "NotNull");
	}

	private boolean asBoolean(Object value) {
		if (value instanceof Boolean bool) {
			return bool;
		}
		if (value == null) {
			return false;
		}
		return Boolean.parseBoolean(String.valueOf(value));
	}

	private int toInt(Object value, int fallback) {
		if (value == null) {
			return fallback;
		}
		try {
			return Integer.parseInt(String.valueOf(value));
		} catch (NumberFormatException ex) {
			return fallback;
		}
	}

	private String defaultIfBlank(String value, String fallback) {
		return value == null || value.isBlank() ? fallback : value;
	}

	private Object nonNull(Object first, Object second) {
		return first != null ? first : second;
	}

	private String restConfigValue(Map<String, Object> restConfig, Object... keys) {
		return trimmed(getNested(restConfig, keys));
	}

	private void removeEmptyList(Map<String, Object> map, String key) {
		Object value = map.get(key);
		if (value instanceof List<?> list && list.isEmpty()) {
			map.remove(key);
		}
	}
}
