package com.src.main.payment.exception;

public enum PaymentErrorCode {
	CONFIG_NOT_FOUND,
	CONFIG_INVALID,
	PROVIDER_UNAVAILABLE,
	ORDER_INVALID_STATE,
	ORDER_NOT_FOUND,
	PAYMENT_NOT_FOUND,
	PAYMENT_INVALID_STATE,
	WEBHOOK_INVALID_SIGNATURE,
	WEBHOOK_INVALID_PAYLOAD,
	GATEWAY_FAILURE,
	RECONCILIATION_FAILURE
}
