package com.src.main.sm.config;

public enum Events {
	START, DTO_DONE, DTO_FAIL, MODEL_DONE, MODEL_FAIL, SWAGGER_DONE, SWAGGER_FAIL, REST_DONE, REST_FAIL, APPFILES_DONE,
	APPFILES_FAIL, DOCKER_DONE, DOCKER_FAIL, SCAFFOLD_DONE, SCAFFOLD_FAIL, FAIL
}
