package com.src.main.sm.config;

public enum Events {
	START, DTO_DONE, DTO_FAIL, ENUM_DONE, ENUM_FAIL, MODEL_DONE, MODEL_FAIL, SWAGGER_DONE, SWAGGER_FAIL, REST_DONE, REST_FAIL, APPFILES_DONE,
	APPFILES_FAIL, CRUD_DONE, CRUD_FAIL, ACTUATOR_DONE, ACTUATOR_FAIL, EXCEPTION_PACKAGE_DONE, EXCEPTION_PACKAGE_FAIL, MAPPER_DONE, MAPPER_FAIL, DOCKER_DONE, DOCKER_FAIL, SCAFFOLD_DONE, SCAFFOLD_FAIL, FAIL
}
