package com.src.main.sm.config;

public enum States {
	DTO_GENERATION, ENUM_GENERATION, MODEL_GENERATION, SWAGGER_GENERATION, REST_GENERATION, CRUD_GENERATION, ACTUATOR_CONFIGURATION, APPLICATION_FILES, DOCKER_GENERATION, SCAFFOLD, DONE, ERROR
}
